# Build settings

port: 4000
markdown:  kramdown
permalink: /:title  
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]
baseurl: "portfolio"

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title: "Home ğŸ‘¨â€ğŸ’»"
description: "Aprendiendo a programar"
author:      "Nahuel"
